#! /usr/bin/env python
"""Predict SCCmec presence of a sample."""
import sys

from ruffus import *

from staphopia.helpers.time_job import time_job
from staphopia.tasks import sccmec, shared

parser = cmdline.get_argparse(description='Predict SCCmec presence.')
parser.add_argument("-f", "--fastq", dest="fastq", help="Input FASTQ file",
                    required=True)
parser.add_argument("--blastdb", dest="blastdb", required=True,
                    help="BLAST database to query genes against.")
parser.add_argument('-p', '--processors', metavar="INT", type=int, default=1,
                    help='Number of processors to use. (Default 1)')
parser.add_argument("-r", "--read_length", dest="read_length", type=int,
                    help="Mean read length of input FASTQ file", metavar="INT",
                    default=0)
parser.add_argument('--paired', action='store_true', default=False,
                    help='Input is interleaved paired end reads.', )
parser.add_argument('--log_times', action='store_true', default=False,
                    help='Write task run times to file (Default: STDERR).', )
options = parser.parse_args()
blastdb_exists = options.blastdb + ".out"

TIME_LOG = 'logs/predict_sccmec.time' if options.log_times else sys.stderr
# Pipeline --------------------------------------------------------------------
read_length = options.read_length
if not options.read_length:
    # Try to read a stats file
    try:
        stats = options.fastq.replace('gz', 'stats')
        with open(stats, 'r') as f:
            json_data = json.loads(f.readline().rstrip())
            read_length = json_data['mean_read_length']
    except:
        # Unknown read length, set to 0 and use BWA aln/samse
        read_length = 0


@active_if(options.log_times)
def create_dir():
    """Make logs directory if required."""
    out, err = shared.run_command(['mkdir', 'logs'])


@mkdir('sccmec')
@transform(blastdb_exists, regex(r"(.*)"), r"sccmec/completed.proteins")
@time_job(TIME_LOG, new_stream=True)
def blast_genes(blastdb, output_file):
    """Blast SCCmec related genes against given blast database."""
    sccmec.blast_genes(options.blastdb, output_file, str(options.processors))


@follows(blast_genes)
@transform(blastdb_exists, regex(r"(.*)"), r"sccmec/completed.primers")
@time_job(TIME_LOG)
def blast_primers(blastdb, output_file):
    """Blast SCCmec related primers against given blast database."""
    sccmec.blast_primers(options.blastdb, output_file)


@mkdir('sccmec/cassettes')
@follows(blast_primers)
@transform(options.fastq, regex(r"(.*)"), r"sccmec/cassettes/completed.sam")
@time_job(TIME_LOG)
def bwa(input_file, completed_file):
    """Align reads using BWA."""
    output_sam = completed_file.replace('completed', 'sccmec')

    if (read_length > 70):
        # Run BWA mem
        sccmec.bwa_mem(options.fastq, output_sam, str(options.processors),
                       options.paired, completed_file)
    else:
        # Run BWA aln/samse
        sai = output_sam.replace('sam', 'sai')
        sccmec.bwa_aln(options.fastq, sai, output_sam, str(options.processors),
                       completed_file)


@follows(bwa)
@transform(bwa, regex(r"(.*).sam"), r"\1.bam")
@time_job(TIME_LOG)
def sam_to_bam(input_file, output_file):
    """Convert SAM  to BAM."""
    sccmec.sam_to_bam(input_file, output_file)


@follows(sam_to_bam)
@transform(sam_to_bam, regex(r"(.*).bam"), r"\1.coverage")
@time_job(TIME_LOG)
def genome_coverage_bed(input_file, output_file):
    """Calculate coverage of the alinged reads."""
    sccmec.genome_coverage_bed(input_file, output_file)


@follows(genome_coverage_bed)
@transform(genome_coverage_bed, regex(r"(.*).coverage"), r"\1.cleanup")
@time_job(TIME_LOG)
def cleanup_mapping(input_file, output_file):
    """Clean up all the intermediate files."""
    sccmec.cleanup_mapping(output_file)

# -----------------------------------------------------------------------------
pipeline_run(exceptions_terminate_immediately=True, verbose=5)
