#! /usr/bin/env python
""" Test input file to determine if it is a valid FASTQ file. """
import sys

from ruffus import *

from staphopia.helpers.time_job import time_job
from staphopia.tasks import fastq, shared

parser = cmdline.get_argparse(description='Validate FASTQ files')
parser.add_argument("-f", "--fastq", dest="fastq", required=True,
                    help="Compressed FASTQ file (*.tar.gz)",)
parser.add_argument('--log_times', action='store_true', default=False,
                    help='Write task run times to file (Default: STDERR).', )
options = parser.parse_args()

TIME_LOG = 'logs/fastq_validator.time' if options.log_times else sys.stderr
# Pipeline --------------------------------------------------------------------


@active_if(options.log_times)
def create_dir():
    """ Make logs directory if required. """
    out, err = shared.run_command(['mkdir', 'logs'])


@transform(options.fastq, regex(r"(.*)"), r"\1.stats")
@time_job(TIME_LOG, new_stream=True)
def validate(input_file, output_file):
    """ Test validity of FASTQ file. """
    print fastq.validator(options.fastq)


# -----------------------------------------------------------------------------
pipeline_run(exceptions_terminate_immediately=True, verbose=0)
